removing the sample-db-utils as required and moving to extra
brazil-data-cube/sampledb pull request #62
Opened 2021-06-30 22:05 UTC by fabianazioti

2021-07-01 17:29 UTC, GSansigolo approved these changes

2021-07-05 11:36 UTC, raphaelrpl requested changes

2021-07-05 11:36 UTC, raphaelrpl commented on sample_db/models/dataset_table.py
> +        print(err)
Please use library `logging` instead

2021-07-05 18:59 UTC, raphaelrpl approved these changes

2021-07-07 12:35 UTC, merged